import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import Card from "../components/card/Card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="test@gmail.com" />

      <Banner
        title="some cool title"
        subTitle="some cool subtitle"
        imgUrl="/static/test-image.png"
      />
      <Card imgUrl="/static/test-image.png" size="large" />
      <Card imgUrl="/static/test-image.png" size="medium" />
      <Card imgUrl="/static/test-image.png" size="small" />
    </div>
  );
}
